name: Ubuntu

on:
  schedule:
    - cron: "30 1 * * *" # In UTC ( 7 AM IST)

jobs:
  myubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build and Push Noble
        run: |
          docker login -u capriciousduck -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker build --build-arg distro=noble -t capriciousduck/myubuntu:noble .
          docker push capriciousduck/myubuntu:noble

      - name: Build and Push Jammy
        run: |
          docker login -u capriciousduck -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker build --build-arg distro=jammy -t capriciousduck/myubuntu:jammy .
          docker push capriciousduck/myubuntu:jammy
      
