name: Ubuntu

on:
  workflow_dispatch

jobs:
  myubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build and Push
        run: |
          docker login -u capriciousduck -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker build --build-arg distro=noble -f Dockerfile.noble -t capriciousduck/myubuntu:noble .
          docker push capriciousduck/myubuntu:noble
      
